### ISSUE TITLE
dont work

### ISSUE THREAD

**Issue by yasarguner** [Cyrexxis/RokTracker#1]
have any problem ?

**Comment by Citrona** [comment]
Hi, describe your problem more if you want to get help

**Comment by yasarguner** [comment]
hi bro problem is pip version but im update but thesame problem

**Comment by yasarguner** [comment]
python.exe -m pip install --upgrade pip 
Requirement already satisfied: pip in c:\users\asdasd\appdata\local\programs\python\python311\lib\site-packages (23.0.1)

**Comment by Cyrexxis** [comment]
Hello, from the screenshot it looks like a problem with the installation of some packages. It seems like it wants to complile them but doesn't have a c++ compiler installed. That should be fixed if you follow the link it gives you and install the "Visual CPP Build Tools".
