### ISSUE TITLE
Add Python version check to rok-scanner.py 

### ISSUE THREAD

**Issue by theCyberTech** [Cyrexxis/RokTracker#10]
**Is your feature request related to a problem? Please describe.**
As presented in https://github.com/Cyrexxis/RokTracker/issues/9, users may experience Python errors if they are not running the correct, specified version.

The issue specific to issue 8 is that Python 3.9 and below do not allow using a | (pipe) as a union operator in the function (This is how I understand it). This was remediated in version 3.10 with PEP 604.

**Describe the solution you'd like**
Add a simple Python version check at the top of rok-scanner.py.

 `
import sys

required_version = (3, 11)  # Replace with the required version tuple, e.g., (3, 9) for Python >
current_version = sys.version_info

if current_version < required_version:
    print(f"Update required: Current Python version is {current_version.major}.{current_version>
          f"but version {required_version[0]}.{required_version[1]} or higher is needed.")
    sys.exit(1)
`

**Describe alternatives you've considered**
The alternative is to "downgrade" the code specific to issue 8 to remediate the issue but I believe this is not warranted as venv is already used which means that it can be utilized to create a Python 3.11 environment but that would require a bit more planning to implement into the script .

**Additional context**
Nothing else to add really, forcing upgrade to the latest stable version of Python is a good thing in general as this is not an enterprise app and the majority of use cases would not have customized Python environments.

**Comment by Cyrexxis** [comment]
Very good idea and nice explanation. I'll do that.
