### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Goddess420** [Cyrexxis/RokTracker#107]
![Screenshot 2024-11-02 020957](https://github.com/user-attachments/assets/2a927890-1b0a-461b-9fa2-433bff138ef5)

I keep getting this error message when I run Kingdom Scanner. I've followed all the steps listed with advanced installation instructions

**Comment by Cyrexxis** [comment]
Hello sorry for the late response. It looks like something is wrong in the json config file. Probably the path to the bluestacks config. In json you need to use ```\\``` instead of ```\``` otherwise you get this error.
