### ISSUE TITLE
[BUG] Gov ID not scanning properly or consistently

### ISSUE THREAD

**Issue by mfinholt** [Cyrexxis/RokTracker#110]
**Describe the bug**
On the 5.0.0 release, everything is working perfectly but I'm not getting consistent data for the Governor ID
Examples:
 - No data is returned (most of the time)
 - Partial ID is returned (some of the time)
 - Complete correct ID is returned (rarely)

This only started today with the new release of ROK and your scanner. 

No errors are thrown but incorrect data is returned for GovID. I've been able to reproduce in both advanced mode and with the GUI. 

In an effort to troubleshoot, I've: 
 - done complete reinstalls of all packages for both GUI and Advanced command-line mode
 - upgraded bluestacks
 - verified all bluestacks settings and configurations
 - attempted both advanced and gui modes
 - computer reboots

**Your Setup (please complete the following information):**
 - OS: Win 11 Pro
 - Bluestacks Version: 5.21.600.1019
 - Android of Bluestacks: Pie 64-bit
 - Python 3.12.4 (for advanced mode)

**Comment by mfinholt** [comment]
Update: I suspect that this is caused by the fade-out animation from the "Nickname Successfully Copied" overlay. 
I tested by uncommenting the time.sleep line in roktracker/kingdom/scanner.py (292)
https://github.com/Cyrexxis/RokTracker/blob/d1f1023f7a7c9841ac2e06cef7308979069a9fa9/roktracker/kingdom/scanner.py#L292

Suggested resolutions:
 - move the nickname copy logic below the screen capture of gov info
 - introduce a delay (least preferable since is extends the scan time)

**Comment by Cyrexxis** [comment]
Ah, thank you for this observation. I think this is the real cause of the issue from #108. I probably didn't notice that because my rok scanner runs very slowly. Both suggested resolutions are easy to implement, and I agree with you that moving the copy to after id scan is the preferred solution (the wait time got commented out to increase the speed; it would be bad to add it back). I will release a hotfix later today.

**Comment by Cyrexxis** [comment]
This should be fixed in Version 5.0.1
