### ISSUE TITLE
[BUG]how to update pip in venv???

### ISSUE THREAD

**Issue by quannv98k3** [Cyrexxis/RokTracker#15]

**Comment by Cyrexxis** [comment]
Hello, that has nothing to do with this project and is also not needed (as long as you have python 3.11). That is basic python stuff and it also should say in the message what to do. 

![Code_2023-07-06_14-56-10](https://github.com/Cyrexxis/RokTracker/assets/4398383/36b70d35-e726-49bb-8f9a-e0ae75c1302d)

There in the To update line it states excatly what you need to do. Just run `python -m pip install --upgrade pip` while your venv is active.

I am going to close this issue, if i understood your problem wrong feel free to reopen this and provide more info.
