### ISSUE TITLE
[BUG] Profile page updates

### ISSUE THREAD

**Issue by leonyonz** [Cyrexxis/RokTracker#17]
Hi @Cyrexxis 
Sad to inform you, the profile page in game has been change after new updates
![image](https://github.com/Cyrexxis/RokTracker/assets/42370275/59824081-39da-4161-8231-ddec4684c5fc)

i dont think this amazing bot will work anymore :(

**Comment by leonyonz** [comment]
seems only on PC Mode,
Wrong alert sorry

**Comment by Cyrexxis** [comment]
Thanks for mentioning, that would have been fixable with adjusting where to tap and where to read text. So if this change ever comes to the android version i will update the bot accordingly.
