### ISSUE TITLE
[BUG] What happened???

### ISSUE THREAD

**Issue by quannv98k3** [Cyrexxis/RokTracker#21]
Adb port of device (5555):
Kingdom name (used for file name) (KD): 2655
People to scan (600): 500
Resume scan [y/n] (n):
Use the new scrolling method (more accurate, but might not work) [y/n] (y):
Track inactives (via screenshot) [y/n] (n):
Try to reconstruct kills via killpoints [y/n] (y):
Starting adb server and connecting to adb device...
* daemon not running; starting now at tcp:57144
* daemon started successfully
connected to localhost:5555

Traceback (most recent call last):
  File "D:\RokTracker\rok-scanner.py", line 934, in <module>
    main()
  File "D:\RokTracker\rok-scanner.py", line 922, in main
    scan(
  File "D:\RokTracker\rok-scanner.py", line 643, in scan
    governor = governor_scan(
               ^^^^^^^^^^^^^^
  File "D:\RokTracker\rok-scanner.py", line 241, in governor_scan
    with PyTessBaseAPI(path="./deps/tessdata-main") as api:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "tesserocr.pyx", line 1219, in tesserocr._tesserocr.PyTessBaseAPI.__cinit__
  File "tesserocr.pyx", line 1233, in tesserocr._tesserocr.PyTessBaseAPI._init_api
RuntimeError: Failed to init API, possibly an invalid tessdata path: ./deps/tessdata-main
Press Enter to continue...:

**Comment by quannv98k3** [comment]
I created "deps" folders in "D:\" so do i right or wrong?

**Comment by markm-io** [comment]
Yes but you also have to make sure that you are downloading the files from the Readme [https://github.com/tesseract-ocr/tessdata](url) and unzipping that and putting the tessdata-main in the deps folder

**Comment by Cyrexxis** [comment]
Assuming you start the script when you are in the folder `D:\RokTracker` the deps folder should be in the RokTracker folder: `D:\RokTracker\deps`. And like mark mentioned in that folder should be a `tessdata-main` folder with the tesseract traineddata files.

**Comment by quannv98k3** [comment]
> 

many thanks, it solved
