### ISSUE TITLE
[BUG] Just scrolling through the power rankings and not opening player profiles

### ISSUE THREAD

**Issue by TreZc0** [Cyrexxis/RokTracker#22]
**Describe the bug**

**To Reproduce**
1. Bluestacks up according to README
2. Opening Power Rankings through Settings => Search Governor
3. Setup for tool, start of rok-scanner.py.
4. Tool is just skipping through the list and not opening actual profiles

**Expected behavior**
Tool should be opening every single user and tracking stats

**Screenshot**
![image](https://github.com/Cyrexxis/RokTracker/assets/12583689/18a7def5-802c-4502-9d7b-a442046a1500)

**Your Setup (please complete the following information):**
 - OS: WIn11
 - Bluestacks Version: 5.4.100.1026
 - Main Branch

**Additional context**
Maybe I am misunderstanding the instructions in the readme, but the Search Governor view is the one I should use, right? if not, it would be awesome if we could get an explanation on how to get to the right screens.

**Comment by markm-io** [comment]
No you should be going to the ranking page. You get there by clicking on your profile photo to the top left and then clicking on **Rankings** and then **Individual Rankings** and that is the menu you want to be at

**Comment by TreZc0** [comment]
Sorry lol, I really didn't know this screen so far...embarassing. Thank you
