### ISSUE TITLE
Improvement README.md

### ISSUE THREAD

**Issue by leonyonz** [Cyrexxis/RokTracker#25]
Hi Cyrexxis your tools working well in my device everytime i install it.

Just want let you know, i think the installation section [Here](https://github.com/Cyrexxis/RokTracker#installation) missing instruction to create `deps` folder in somewhere location on device. 

I know it simple :D but i bit confuse when reinstalling this tools on different device by reading the instruction hahaha.

Again, sorry to annoy you :)

**Comment by Cyrexxis** [comment]
Oh yeah true. I will update the readme accordingly.
