### ISSUE TITLE
Update Alliance / Honor scanner

### ISSUE THREAD

**Issue by Cyrexxis** [Cyrexxis/RokTracker#38]
**Is your feature request related to a problem? Please describe.**
The alliance and kingdom scanner didn't get updated since version 1.0, they need to get migrated to new adb and tesseract.

**Describe the solution you'd like**
Update the scripts, but **I will not add a GUI to that scanner**, I don't even know how many people use that scanner.

**Comment by leonyonz** [comment]
Need title bot please :D
