### ISSUE TITLE
[BUG] how to upgraded pip version in local venv???

### ISSUE THREAD

**Issue by quannv98k3** [Cyrexxis/RokTracker#40]
Please show me the way to update pip version of venv

**Comment by Citrona** [comment]
- Open Powershell in Administrator mode
- Replace with your path  `cd "C:\RoktTracker"`
- Type `python -m venv ./venv`
- Type `invoke-expression -Command .\venv\Scripts\Activate.ps1`
- Type `python -m pip install --upgrade pip`
- Done

**Comment by Cyrexxis** [comment]
Yes exactly what Citrona said, but it should run without needing to upgrade pip, also that is not an issue of this project. I am going to close the issue.
