### ISSUE TITLE
Installing Requirements not working

### ISSUE THREAD

**Issue by TheAnonymous13** [Cyrexxis/RokTracker#42]
**Describe the bug**
When following the advanced installation steps, the venv will not install properly, or it will not connect with the requirements_win64.txt

**To Reproduce**
1. Follow the advanced installation steps until you hit step number 6 under setup
2. Follow step number 6 

**Expected behavior**
The requirements are installed

**Screenshots**
This is the error i am running into:
<img width="466" alt="Screenshot 2023-12-10 162252" src="https://github.com/Cyrexxis/RokTracker/assets/145536903/1b604713-25d0-494f-8530-73198d91e9b3">

This is what my files look like:
<img width="113" alt="Screenshot 2023-12-10 162357" src="https://github.com/Cyrexxis/RokTracker/assets/145536903/c550cea5-81a8-465b-8652-97143657fb1f">

Any help would be appriciated, slide into my discord here:
anonymous_2018

**Comment by Cyrexxis** [comment]
This got resolved. Closing the issue.
