### ISSUE TITLE
Stopped to work after rok update[BUG]

### ISSUE THREAD

**Issue by WoWHellgarve-HolyDeeW** [Cyrexxis/RokTracker#48]
After trying to scan top 300 the scanner clicks on champions of olimpia instead and cannot find the kills and other usefull data details 
So the bot just stops work saying cannot find the governor.
Thank you for your work.

**Comment by Citrona** [comment]
Hey, can you tell us which tracker version you're using? And can you send us a screen of your bluestacks interface during the scan please. Thanks

**Comment by WoWHellgarve-HolyDeeW** [comment]
hi, i am using the newest version.. i did 3 scans on that day all were fine.. and then i updated the game to latest version and it stopped to work.. i will manage to send you a printscreen when i got home, btw did you updated the game yet? to try replicate this issue?
thank you ^^

**Comment by Citrona** [comment]
I do one scan a day with the latest version and I have no problems lol, a bluestacks update has probably changed your resolution ^^

**Comment by WoWHellgarve-HolyDeeW** [comment]
![image](https://github.com/Cyrexxis/RokTracker/assets/87277682/4ce64c03-8c00-44b6-a94b-00ac68940a2a)
![image](https://github.com/Cyrexxis/RokTracker/assets/87277682/4b8ceb70-5c15-4c79-b340-645b495fd2e2)
![image](https://github.com/Cyrexxis/RokTracker/assets/87277682/995b40c8-cb16-4677-9d7a-1c5d4258515b)

**Comment by Citrona** [comment]
Change the resolution to a lower one, restart bluestacks and reset to 1600x900, and restart, and try please

**Comment by WoWHellgarve-HolyDeeW** [comment]
my res settings -> 
![image](https://github.com/Cyrexxis/RokTracker/assets/87277682/f9d1f6df-3e91-47f7-9448-9ab94a6224de)
hes keep clicking here -> 
![image](https://github.com/Cyrexxis/RokTracker/assets/87277682/2d22e39c-4642-46b8-86e5-4ac9c88abe64)
![image](https://github.com/Cyrexxis/RokTracker/assets/87277682/e82f0200-1dd7-4f0c-ad22-98b6f135ade7)

**Comment by WoWHellgarve-HolyDeeW** [comment]
> Change the resolution to a lower one, restart bluestacks and reset to 1600x900, and restart, and try please

i will, thank you sir

**Comment by WoWHellgarve-HolyDeeW** [comment]
> Ok I get it, set your game language to English, the script must read the "More info" to perform the data collection. This is the procedure for checking whether an account is inactive

awsome that worked.. thank you^^ also i could make a pr to fix that for other languages if you like it

**Comment by WoWHellgarve-HolyDeeW** [comment]
fixed
