### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by hcw001** [Cyrexxis/RokTracker#49]
Hi Cyrexxis,

While trying to install the Rok Trakker (GUI) following the Simple Installation instructions I encountered this error:

"
Failed to execute script pyi_rth__tkinter due to unhandled exception: Tk data directory " C:\Users\ccc\OneDrive\Desktop\RoK Tracker (GUI)\_internal\tk" not found

Trackback (most recent call last):
File "PyInstaller\hooks\rthooks\pyi_rth__tkinter.py" line 35, in <modules>
File "PyInstaller\hooks\rthooks\pyi_rth__tkinter.py" line 32, in _pyi_rthook
FileNotFoundError: Tk data directory "C:\Users\ccc\OneDrive\Desktop\RokTracker (GUI)\_internal\tk" not found.
"

Do you have any idea what I have done wrong?
I have attached the tree of my installation.

[tree.txt](https://github.com/Cyrexxis/RokTracker/files/13762818/tree.txt)

Thank you,
Hayden

**Comment by Cyrexxis** [comment]
Hm very interesting error. The path it shows you is missing a backslash. ```C:\Users\ccc\OneDrive\Desktop\RokTracker (GUI)_internal\tk``` should be ```C:\Users\ccc\OneDrive\Desktop\RokTracker (GUI)\_internal\tk```. But that should be handled by the pyinstaller package i use to bundle the .exe file. Can you redownload the zip and try again?

**Comment by hcw001** [comment]
Redownloading the zip worked. Very strange error indeed. I had some more trouble getting the GUI to work but have had success running the console version through the virtual environment. Thank you, very cool project!

**Comment by Cyrexxis** [comment]
Can you tell me a bit more about the trouble you got with the GUI? Maybe I can make it easier to understand in the readme or handle it in some other way. If nothing else is going wrong i probably will close this issue.

**Comment by hcw001** [comment]
Something that could be helpful to add to the READ_ME: look for bluestacks.conf in ProgramData\Bluestacks_nxt\bluestacks.conf (I was not familiar with bluestacks before this and it was not intuitive to me that the config file would be saved here)

**Comment by hcw001** [comment]
Also may be helpful to mention that bluestacks instance name can be changed in the bluestacks.conf file

**Comment by Cyrexxis** [comment]
Ok, yeah i will add that to the next version of the readme. The strange thing with bluestacks is that not every version has the .conf file (the version without .conf always uses port 5555). Also the error you got from the UI looks like you wrote an invalid number in the "people to scan" field. Probably that should be handled by showing a popup that mentions it instead of simply doing nothing.

**Comment by hcw001** [comment]
Ahh oops! I found a thread detailing that exact Bluestakcs issue. I switched my installation to use port 3389 as I feared my security software might be blocking port 5555. 

Thanks for the help.

**Comment by Cyrexxis** [comment]
I think everything is resolved now and I am going to close this issue.
