### ISSUE TITLE
Testing alliance / honor scanner

### ISSUE THREAD

**Issue by Cyrexxis** [Cyrexxis/RokTracker#6]
Hello,

I want to find out how independent the new scrolling with events is (because if it works for everyone, I will also use it in the normal scanner due to much increased precision).
To find that out, it would be nice to have different setups from different people, so I encourage everyone to test the new `alliance-scanner.py` script and take a look how accurate the scrolling is. The expected result is that one scroll moves exactly one player down the list.

Here is a snippet to start the alliance scanner if you already have set up the venv in the venv folder:
```
.\venv\Scripts\Activate.ps1
pip install -r requirements.txt
python alliance-scanner.py
```

If you choose alliance as mode the script expects you to be on one of the alliance leaderboard pages, for honor it expects either the global honor per player or the alliance honor per player view.

Optimal would be to post if it scrolls correct, the blue stacks version and the android version you are using with blue stacks.

Thanks in advance for testing that feature.

**Comment by Cyrexxis** [comment]
Alliance works good.
Honor works good (minimal too much scrolling).
BlueStacks 5.9.350.1035
Nougat 64-bit

**Comment by Citrona** [comment]
I just tried the [last commit](https://github.com/Cyrexxis/RokTracker/commit/c397edb7bcb86cc3e4daaab06ae8baa67a1378b9) and I had the problem when I scan for alliances and players it gets stuck on the number 1 of the ranking and does not scroll no matter how many people I select. 

BlueStacks 5.11.1.1002
Pie 64-bit

**Comment by Citrona** [comment]
When I use mode alliance I get this error message

```
Starting adb server and connecting to adb device...
* daemon not running; starting now at tcp:5037
* daemon started successfully
connected to localhost:5595

Traceback (most recent call last):
  File "D:\TT\Documents\Dev\Rok3\alliance-scanner.py", line 269, in <module>
    main()
  File "D:\TT\Documents\Dev\Rok3\alliance-scanner.py", line 264, in main
    scan(int(port), kingdom, mode, int(scan_amount), resume_scan)
  File "D:\TT\Documents\Dev\Rok3\alliance-scanner.py", line 216, in scan
    governor = governor_scan(mode, device, port, i)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\TT\Documents\Dev\Rok3\alliance-scanner.py", line 174, in governor_scan
    gov_score = int(re.sub("[^0-9]", "", gov_score))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: ''
```

**Comment by Cyrexxis** [comment]
Hm, that means the scanner didn't find any text at the score position. Were you in the correct screen? It should look like the attached picture (well, not necessary power, but that screen from the alliance)
![Alliance Censored](https://user-images.githubusercontent.com/4398383/224543780-ae50124f-efaa-4ee8-9c97-398691eedf4c.png)

Or for the honor mode, this screen:
![Honor Censored](https://user-images.githubusercontent.com/4398383/224544105-015bf1d5-3b02-4129-9350-274359e74a45.png)

And in that case it actually makes sense it doesn't scroll, because it crashes on the first person, but still not good.

**Comment by Citrona** [comment]
I just tried again after your answer on the alliance mode but it still blocks on the first person in both options
![image](https://user-images.githubusercontent.com/111499437/224545557-15920e2f-9ae1-451e-bfb7-6d53abcc1499.png)
![image](https://user-images.githubusercontent.com/111499437/224545541-db53feca-e1b9-48dd-a470-0355d123a54d.png)

**Comment by Cyrexxis** [comment]
Yes, I experienced the same behavior and already found the cause of the problem. I will try to fix it in a future commit.
Scrolling does not work on Bluestacks 5.11.1.1004 with Pie 64 bit.

For the people interested in the details: The input events are hard coded to event1 at the moment. On my BlueStacks 5.9.350.1035 with Nougat 64-bit that is the touchscreen (makes sense since I want to simulate a touch) but on Bluestacks 5.11.1.1004 with Pie 64 bit event1 is the keyboard (not good for simulating touch XD) so I will try to choose the right input dynamically if possible. The upside is I tested with event2 (touch screen for the other blue stacks) and it seems the coordinates are still ok, meaning if it uses touch screen input it scrolls like it should (exactly one person)

**Comment by Cyrexxis** [comment]
Ok now after commit 0a4dbae92a0075deaab56f71710d254258346cf5 it seems to work for me on both BlueStacks instances.

Alliance and Honor works as expected.

BlueStacks 5.9.350.1035
Android: Nougat 64-bit

and

BlueStacks 5.11.1.1002
Android: Pie 64-bit

**Comment by Citrona** [comment]
It now works with the latest commit

BlueStacks 5.11.1.1002
Android: Pie 64-bit

**Comment by Citrona** [comment]
Bug: For the honor point scan when I get to the end of the list it only collects the information of the first player in the list. Do you think there is an option to detect that the script is at the end of the list and therefore reads the extra entries?

**Comment by Cyrexxis** [comment]
Ok, nice that it works. Yeah, actually, the bug you mentioned is happening in all the scans (and is known). I am thinking about how to fix it. For the normal kingdom scan, it should be very easy. Probably also for the other scans, if the OCR always gives the same name for the same image.

**Comment by Cyrexxis** [comment]
The scanner now should scan all governors in the alliance/honor/kingdom ranking with the latest commit (78741b6ac7a6e5ab5712f4f23b8a1c1526bbadbe)

**Comment by Citrona** [comment]
I just did an honor scan of my alliance, everything works fine except the last person in the list, I saw the message "Duplicate governor, switching to scan of last governors" but it did not read the last person

**Comment by Cyrexxis** [comment]
Oh, that's true. I didn't think about what would happen if you start the scan with the exact amount of people in the alliance. I will fix that soon.

**Comment by Citrona** [comment]
Everything works correctly, no more duplication when you reach the end of the page, the last member is well read when you select the exact number of members

**Comment by Cyrexxis** [comment]
Closing this issue for now, if problems still appear please open a new issue.
