### ISSUE TITLE
Gathering of Killpoints/Power from Rankings.

### ISSUE THREAD

**Issue by Stormragee** [Cyrexxis/RokTracker#71]
**Is your feature request related to a problem? Please describe.*

Gathering Sum of Power of a Kingdom from Player Power Ranking. 

**Describe the solution you'd like**

Just use the scanner from alliancescanner one to a scan of power of a Kingdom. The solution is almost identical yet it add functionality. The scanner would sum up total power of X amount governors.
 Of course it can output the scanned values in excel like in alliance scanner but its just summed up in the end.
**Describe alternatives you've considered**
Either implementing it into Kingdom Scanner or branch out to new one. 
**Additional context**
It is sometimes required to just check topX power of total kingdom instead of detailed scan of all players, to determine seeding.

**Comment by Cyrexxis** [comment]
That seems a valid point and I will implement it when I have time.
