### ISSUE TITLE
Unhandled exception in script [BUG]

### ISSUE THREAD

**Issue by lukieli** [Cyrexxis/RokTracker#73]
I have followed the exact steps from the simple instalation and I am facing the error in the attachment. 
Am I required to make other changes to the config file?

{
  "scan": {
    "kingdom_name": "",
    "people_to_scan": "",
    "resume": false,
    "advanced_scroll": true,
    "track_inactives": true,
    "validate_kills": true,
    "reconstruct_kills": true,
    "timings": {
      "gov_open": 2,
      "copy_wait": 0.2,
      "kills_open": 1,
      "info_open": 1,
      "info_close": 0.5,
      "gov_close": 1
    }
  },
  "general": {
    "bluestacks_name": "RoK Tracker",
    "bluestacks_config": "C:\ProgramData\BlueStacks_nxt\bluestacks.conf"
  }
}

![image_2024-01-26_232837853](https://github.com/Cyrexxis/RokTracker/assets/157848923/0252fe94-2939-43ae-baca-4dcd0e316bf2)

**Your Setup (please complete the following information):**
 - OS: Windows 11
 - Bluestacks Version:  5.20.10.10003
 - Android of Bluestacks: Pie 64-bit
 - Tracker Version: V4.0.1

**Additional context**

**Comment by Cyrexxis** [comment]
This happens because the config is in json format and you have to 'escape' the `\` by using `\\`. Probably for the future I should include a check that catches that error.

**Comment by lukieli** [comment]
That solved it. You are a true beast brother. Thanks and keep up the good work.
