### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by quannv98k3** [Cyrexxis/RokTracker#9]
(venv) PS D:\RokTracker> D:\RokTracker\rok-scanner.ps1
python : Error: [Errno 13] Permission denied: 'D:\\RokTracker\\venv\\Scripts\\python.exe'
At D:\RokTracker\rok-scanner.ps1:1 char:1
+ python -m venv ./venv
+ ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Error: [Errno 1...ts\\python.exe':String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
pip : WARNING: Ignoring invalid distribution -ip (d:\roktracker\venv\lib\site-packages)
At D:\RokTracker\rok-scanner.ps1:3 char:1
+ pip install -r requirements.txt
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (WARNING: Ignori...\site-packages):String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
WARNING: Ignoring invalid distribution - (d:\roktracker\venv\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (d:\roktracker\venv\lib\site-packages)
WARNING: Ignoring invalid distribution - (d:\roktracker\venv\lib\site-packages)
Requirement already satisfied: androidviewclient==22.5.1 in d:\roktracker\venv\lib\site-packages (from -r requirements.txt (line 1)) (22.5.1)
Requirement already satisfied: commonmark==0.9.1 in d:\roktracker\venv\lib\site-packages (from -r requirements.txt (line 2)) (0.9.1)
Requirement already satisfied: et-xmlfile==1.1.0 in d:\roktracker\venv\lib\site-packages (from -r requirements.txt (line 3)) (1.1.0)
Requirement already satisfied: inquirerpy==0.3.4 in d:\roktracker\venv\lib\site-packages (from -r requirements.txt (line 4)) (0.3.4)
Requirement already satisfied: numpy==1.23.5 in d:\roktracker\venv\lib\site-packages (from -r requirements.txt (line 5)) (1.23.5)
Requirement already satisfied: opencv-python==4.6.0.66 in d:\roktracker\venv\lib\site-packages (from -r requirements.txt (line 6)) (4.6.0.66)
Requirement already satisfied: openpyxl==3.1.1 in d:\roktracker\venv\lib\site-packages (from -r requirements.txt (line 7)) (3.1.1)
Requirement already satisfied: packaging==23.0 in d:\roktracker\venv\lib\site-packages (from -r requirements.txt (line 8)) (23.0)
Requirement already satisfied: pfzy==0.3.4 in d:\roktracker\venv\lib\site-packages (from -r requirements.txt (line 9)) (0.3.4)
Requirement already satisfied: Pillow==9.3.0 in d:\roktracker\venv\lib\site-packages (from -r requirements.txt (line 10)) (9.3.0)
Requirement already satisfied: prompt-toolkit==3.0.38 in d:\roktracker\venv\lib\site-packages (from -r requirements.txt (line 11)) (3.0.38)
Requirement already satisfied: Pygments==2.14.0 in d:\roktracker\venv\lib\site-packages (from -r requirements.txt (line 12)) (2.14.0)
Requirement already satisfied: pytesseract==0.3.10 in d:\roktracker\venv\lib\site-packages (from -r requirements.txt (line 13)) (0.3.10)
Requirement already satisfied: rich==12.6.0 in d:\roktracker\venv\lib\site-packages (from -r requirements.txt (line 14)) (12.6.0)
Requirement already satisfied: wcwidth==0.2.6 in d:\roktracker\venv\lib\site-packages (from -r requirements.txt (line 15)) (0.2.6)
Requirement already satisfied: culebratester-client>=2.0.64 in d:\roktracker\venv\lib\site-packages (from androidviewclient==22.5.1->-r requirements.txt (line 1)) (2.0.64
)
Requirement already satisfied: setuptools in d:\roktracker\venv\lib\site-packages (from androidviewclient==22.5.1->-r requirements.txt (line 1)) (41.2.0)
Requirement already satisfied: matplotlib in d:\roktracker\venv\lib\site-packages (from androidviewclient==22.5.1->-r requirements.txt (line 1)) (3.7.1)
Requirement already satisfied: requests in d:\roktracker\venv\lib\site-packages (from androidviewclient==22.5.1->-r requirements.txt (line 1)) (2.28.2)
Requirement already satisfied: typing-extensions<5.0,>=4.0.0 in d:\roktracker\venv\lib\site-packages (from rich==12.6.0->-r requirements.txt (line 14)) (4.5.0)
Requirement already satisfied: six>=1.10 in d:\roktracker\venv\lib\site-packages (from culebratester-client>=2.0.64->androidviewclient==22.5.1->-r requirements.txt (line 
1)) (1.16.0)
Requirement already satisfied: urllib3>=1.15 in d:\roktracker\venv\lib\site-packages (from culebratester-client>=2.0.64->androidviewclient==22.5.1->-r requirements.txt (l
ine 1)) (1.26.15)
Requirement already satisfied: certifi in d:\roktracker\venv\lib\site-packages (from culebratester-client>=2.0.64->androidviewclient==22.5.1->-r requirements.txt (line 1)
) (2022.12.7)
Requirement already satisfied: python-dateutil in d:\roktracker\venv\lib\site-packages (from culebratester-client>=2.0.64->androidviewclient==22.5.1->-r requirements.txt 
(line 1)) (2.8.2)
Requirement already satisfied: cycler>=0.10 in d:\roktracker\venv\lib\site-packages (from matplotlib->androidviewclient==22.5.1->-r requirements.txt (line 1)) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in d:\roktracker\venv\lib\site-packages (from matplotlib->androidviewclient==22.5.1->-r requirements.txt (line 1)) (4.39.
3)
Requirement already satisfied: kiwisolver>=1.0.1 in d:\roktracker\venv\lib\site-packages (from matplotlib->androidviewclient==22.5.1->-r requirements.txt (line 1)) (1.4.4
)
Requirement already satisfied: importlib-resources>=3.2.0 in d:\roktracker\venv\lib\site-packages (from matplotlib->androidviewclient==22.5.1->-r requirements.txt (line 1
)) (5.12.0)
Requirement already satisfied: pyparsing>=2.3.1 in d:\roktracker\venv\lib\site-packages (from matplotlib->androidviewclient==22.5.1->-r requirements.txt (line 1)) (3.0.9)
Requirement already satisfied: contourpy>=1.0.1 in d:\roktracker\venv\lib\site-packages (from matplotlib->androidviewclient==22.5.1->-r requirements.txt (line 1)) (1.0.7)
Requirement already satisfied: idna<4,>=2.5 in d:\roktracker\venv\lib\site-packages (from requests->androidviewclient==22.5.1->-r requirements.txt (line 1)) (3.4)
Requirement already satisfied: charset-normalizer<4,>=2 in d:\roktracker\venv\lib\site-packages (from requests->androidviewclient==22.5.1->-r requirements.txt (line 1)) (
3.1.0)
Requirement already satisfied: zipp>=3.1.0 in d:\roktracker\venv\lib\site-packages (from importlib-resources>=3.2.0->matplotlib->androidviewclient==22.5.1->-r requirement
s.txt (line 1)) (3.15.0)
WARNING: Ignoring invalid distribution -ip (d:\roktracker\venv\lib\site-packages)
WARNING: Ignoring invalid distribution - (d:\roktracker\venv\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (d:\roktracker\venv\lib\site-packages)
WARNING: Ignoring invalid distribution - (d:\roktracker\venv\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (d:\roktracker\venv\lib\site-packages)
WARNING: Ignoring invalid distribution - (d:\roktracker\venv\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (d:\roktracker\venv\lib\site-packages)
WARNING: Ignoring invalid distribution - (d:\roktracker\venv\lib\site-packages)
python : Traceback (most recent call last):
At D:\RokTracker\rok-scanner.ps1:4 char:1
+ python .\rok-scanner.py
+ ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Traceback (most recent call last)::String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
  File ".\rok-scanner.py", line 10, in <module>
    from adbutils import *
  File "D:\RokTracker\adbutils.py", line 68, in <module>
    def adb_send_events(input_device_name: str, event_file: str | Path, port: int):
TypeError: unsupported operand type(s) for |: 'type' and 'type'

**Comment by theCyberTech** [comment]
First, for your first issue, you can do one of the following: 

- Run the Powershell/cmd terminal as Administrator
- Run the Powershell script as Administrator
- Change the Security permissions on  D:\RokTracker folder and all of its sub-folders

For your second issue, What version of Python are you running? The README.md states Python version 3.11 is required. Run the following command from the cmdline to verify, if it is not version 3.11 then please update Python to version 11 and then rerun the script again:

`python --version`

**Comment by quannv98k3** [comment]
Traceback (most recent call last):
  File ".\rok-scanner.py", line 10, in <module>
    from adbutils import *
  File "D:\RokTracker\adbutils.py", line 68, in <module>
    def adb_send_events(input_device_name: str, event_file: str | Path, port: int):
TypeError: unsupported operand type(s) for |: 'type' and 'type'

**Comment by quannv98k3** [comment]
> > First, for your first issue, you can do one of the following:
> > ```
> > * Run the Powershell/cmd terminal as Administrator
> > 
> > * Run the Powershell script as Administrator
> > 
> > * Change the Security permissions on  D:\RokTracker folder and all of its sub-folders
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > For your second issue, What version of Python are you running? The README.md states Python version 3.11 is required. Run the following command from the cmdline to verify, if it is not version 3.11 then please update Python to version 11 and then rerun the script again:
> > `python --version`
> 
> In addition to that, the first error can also happen if the script is run in the Powershell ISE (integrated scripting environment) instead of the normal powershell. For me personally, I also get the python `Error: [Errno 13] Permission denied: 'D:\RokTracker\venv\Scripts\python.exe'` but the script runs fine.
> 
> For your next issue it would be nice to have a bit more details of what you are doing and also a more meaningful title.
> 
> Also, please respond after trying the steps so that we know if you need further help or if it got resolved.

my python is 3.8.0 so do i need to upgrade?

**Comment by theCyberTech** [comment]
Yes, before you try running this tool again you need to  upgrade to Python version 3.11 as per the instructions

**Comment by quannv98k3** [comment]
Just update and still cant run it.

Traceback (most recent call last):
  File "D:\RokTracker\rok-scanner.py", line 10, in <module>
    from adbutils import *
  File "D:\RokTracker\adbutils.py", line 2, in <module>
    from PIL.Image import Image, new as NewImage
  File "D:\RokTracker\venv\Lib\site-packages\PIL\Image.py", line 100, in <module>
    from . import _imaging as core
ImportError: cannot import name '_imaging' from 'PIL' (D:\RokTracker\venv\Lib\site-packages\PIL\__init__.py)

**Comment by quannv98k3** [comment]
I removed the old file and download new one, It run but still have error

[notice] A new release of pip available: 22.3 -> 23.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip
The UUID of this scan is j5ubd289
Could not parse or find bluestacks config. Defaulting to 5555.
Adb port of device (5555): 5555
Kingdom name (used for file name) (KD): 2655
People to scan (600):
Resume scan [y/n] (n):
Use the new scrolling method (more accurate, but might not work) [y/n] (y):
Track inactives (via screenshot) [y/n] (n):
Try to reconstruct kills via killpoints [y/n] (y):
Starting adb server and connecting to adb device...
* daemon not running; starting now at tcp:59210
* daemon started successfully
connected to localhost:5555

Traceback (most recent call last):
  File "D:\RokTracker\venv\Lib\site-packages\pytesseract\pytesseract.py", line 255, in run_tesseract
    proc = subprocess.Popen(cmd_args, **subprocess_args())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\quann\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1022, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\quann\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1491, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\RokTracker\rok-scanner.py", line 676, in <module>
    main()
  File "D:\RokTracker\rok-scanner.py", line 672, in main
    scan(bluestacks_port, kingdom, scan_amount, resume_scan, track_inactives, reconstruct_fails)
  File "D:\RokTracker\rok-scanner.py", line 513, in scan
    governor = governor_scan(port, next_gov_to_scan, inactive_players, track_inactives)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\RokTracker\rok-scanner.py", line 175, in governor_scan
    check_more_info = pytesseract.image_to_string(im_check_more_info,config="-c tessedit_char_whitelist=MoreInfo")
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\RokTracker\venv\Lib\site-packages\pytesseract\pytesseract.py", line 423, in image_to_string
    return {
           ^
  File "D:\RokTracker\venv\Lib\site-packages\pytesseract\pytesseract.py", line 426, in <lambda>
    Output.STRING: lambda: run_and_get_output(*args),
                           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\RokTracker\venv\Lib\site-packages\pytesseract\pytesseract.py", line 288, in run_and_get_output
    run_tesseract(**kwargs)
  File "D:\RokTracker\venv\Lib\site-packages\pytesseract\pytesseract.py", line 260, in run_tesseract
    raise TesseractNotFoundError()
pytesseract.pytesseract.TesseractNotFoundError: tesseract is not installed or it's not in your PATH. See README file for more information.

**Comment by Cyrexxis** [comment]
Ok, happy you got it to work. In theory, it should work when Tesseract is on the PATH, but good that it works that way too. I'll probably add an optional tesseract install location variable, like the original Rok Tracker. That should allow more ways to install Tesseract.
