### ISSUE TITLE
Add support for LD player

### ISSUE THREAD

**Issue by Cyrexxis** [Cyrexxis/RokTracker#98]
**Is your feature request related to a problem? Please describe.**
Currently the scanner goes into "no user found" mode when more than 10 inactive govs come after each other.

**Describe the solution you'd like**
Make the number configurable or completely rework the detection mechanism. Currently I am more inclined for a new mechanism.

**Comment by Cyrexxis** [comment]
That is a combination of using LD-Player instead of bluestacks and the fact that advanced scrolling config gets ignored.

Three things need to get adressed:

- [ ] Add config item to configure if bluestacks or ld player is used
- [ ] Add additional scrolling scripts to support LD-Player
- [ ] Fix the advanced scrolling option

**Comment by Cyrexxis** [comment]
Done for now, need to wait for kvk to get the honor scrolling script.

**Comment by GravityPython** [comment]
Hi Cyrexxis, 
Is there a setup for LDplayer in the config file ?  I haven't been successful to make it work with LDplaer. Please give guidance. Thanks

**Comment by Cyrexxis** [comment]
Hi, it should work when you set the emulator to ```ld``` in the config. However the honor scanner currently does not work with LD Player. If it still doesn't work I need to look at it again.
